### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/ft-media#21]
```[tasklist]
### Stories
- [x] Optimize all Images during upload based on
- [x] Set featured image automatically to the image, that was uploaded first
- [ ] https://github.com/figuren-theater/ft-media/issues/9
```

```[tasklist]
### Plugins
- [x] Attachment taxonomies
- [x] Format media titles
- [x] Modern Images WP
```
